Vladimir Kuprin module 0, task-1
js-tasks-ru/jsbasic-20211108_gufcher pull request #1
Opened 2021-11-10 22:29 UTC by VladimirKuprin

2021-11-10 22:29 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2021-11-11 12:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-11 12:57 UTC, SinimaWath requested changes

2021-11-11 12:57 UTC, SinimaWath commented on 0-module/1-task/index.js
> +let otherResult = sum(2, 5);
Из задач, нужно убирать информацию для тестирования:

- Они могут поломать другие тесты
- В задачах не требуется, оставлять какой-то код, кроме необходимой функциональности.

2021-11-14 13:36 UTC, SinimaWath approved these changes
все ок

2021-11-14 13:37 UTC, merged